/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.bean.User;

/**
 *
 * @author Minh_PC
 */
public class FrMain extends javax.swing.JFrame {

    private User objUser;   

    //private JPanel pnCat= new PnCat();
    /**
     * Creates new form FrMain
     */
    public FrMain(User user) {

        initComponents();
        this.objUser= user;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagess/icon.png")).getImage());
//        lbMsg.setText(objUser.getFullName());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        pnLabel = new javax.swing.JPanel();
        lbMsg = new javax.swing.JLabel();
        pnButton = new javax.swing.JPanel();
        btDanhMucTin = new javax.swing.JButton();
        btTinTuc = new javax.swing.JButton();
        btNguoidung = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        btThemDanhMuc = new javax.swing.JButton();
        btThemTinTuc = new javax.swing.JButton();
        btThemNguoiDung = new javax.swing.JButton();
        pnBottom = new javax.swing.JPanel();
        lbButtom = new javax.swing.JLabel();
        mnbTop = new javax.swing.JMenuBar();
        mnChucNang = new javax.swing.JMenu();
        mniTrangChu = new javax.swing.JMenuItem();
        mniTacGia = new javax.swing.JMenuItem();
        mnThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTop.setLayout(new java.awt.BorderLayout());

        lbMsg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMsg.setText("::NewsApp::");
        pnLabel.add(lbMsg);

        pnTop.add(pnLabel, java.awt.BorderLayout.SOUTH);

        pnButton.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        btDanhMucTin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDanhMucTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/qlcat.png"))); // NOI18N
        btDanhMucTin.setText("<html>Quản Lý <br />Danh Mục Tin</html>");
        btDanhMucTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDanhMucTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDanhMucTinActionPerformed(evt);
            }
        });
        pnButton.add(btDanhMucTin);

        btTinTuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTinTuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/qlnews.png"))); // NOI18N
        btTinTuc.setText("<html>Quản Lý <br />Tin Tức</html>");
        btTinTuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTinTuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btTinTucMousePressed(evt);
            }
        });
        pnButton.add(btTinTuc);

        btNguoidung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNguoidung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/qluser.png"))); // NOI18N
        btNguoidung.setText("<html>Quản Lý <br />Người Dùng</html>");
        btNguoidung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btNguoidungMousePressed(evt);
            }
        });
        pnButton.add(btNguoidung);

        pnTop.add(pnButton, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnTop, java.awt.BorderLayout.NORTH);

        pnCenter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnCenter.setLayout(new java.awt.BorderLayout());

        pnMain.setLayout(new java.awt.GridLayout(1, 0));

        btThemDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThemDanhMuc.setForeground(new java.awt.Color(0, 255, 51));
        btThemDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/if_icon-105-folder-add_314789.png"))); // NOI18N
        btThemDanhMuc.setText("Thêm Danh Mục");
        btThemDanhMuc.setBorderPainted(false);
        btThemDanhMuc.setContentAreaFilled(false);
        btThemDanhMuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThemDanhMuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemDanhMuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemDanhMucActionPerformed(evt);
            }
        });
        pnMain.add(btThemDanhMuc);

        btThemTinTuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThemTinTuc.setForeground(new java.awt.Color(0, 255, 51));
        btThemTinTuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/if_newspaper_328053.png"))); // NOI18N
        btThemTinTuc.setText("Thêm Tin Tức");
        btThemTinTuc.setBorderPainted(false);
        btThemTinTuc.setContentAreaFilled(false);
        btThemTinTuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThemTinTuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemTinTuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemTinTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemTinTucActionPerformed(evt);
            }
        });
        pnMain.add(btThemTinTuc);

        btThemNguoiDung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThemNguoiDung.setForeground(new java.awt.Color(204, 51, 0));
        btThemNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/if_user_add_66907.png"))); // NOI18N
        btThemNguoiDung.setText("Thêm Người Dùng");
        btThemNguoiDung.setBorderPainted(false);
        btThemNguoiDung.setContentAreaFilled(false);
        btThemNguoiDung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThemNguoiDung.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemNguoiDung.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemNguoiDungActionPerformed(evt);
            }
        });
        pnMain.add(btThemNguoiDung);

        pnCenter.add(pnMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pnBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbButtom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbButtom.setText("<html>Copyright &copy; By BIKT </html>");
        pnBottom.add(lbButtom);

        getContentPane().add(pnBottom, java.awt.BorderLayout.SOUTH);

        mnbTop.setPreferredSize(new java.awt.Dimension(168, 40));

        mnChucNang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/setting.png"))); // NOI18N
        mnChucNang.setText("Chức Năng");
        mnChucNang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnChucNang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnChucNangMousePressed(evt);
            }
        });

        mniTrangChu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        mniTrangChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mniTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/homepage.png"))); // NOI18N
        mniTrangChu.setText("Trang Chủ");
        mniTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTrangChuActionPerformed(evt);
            }
        });
        mnChucNang.add(mniTrangChu);

        mniTacGia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mniTacGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mniTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/auhtor.png"))); // NOI18N
        mniTacGia.setText("Tác Giả");
        mniTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mniTacGiaMouseReleased(evt);
            }
        });
        mnChucNang.add(mniTacGia);

        mnbTop.add(mnChucNang);

        mnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/exit.png"))); // NOI18N
        mnThoat.setText("Thoát");
        mnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnThoatMousePressed(evt);
            }
        });
        mnbTop.add(mnThoat);

        setJMenuBar(mnbTop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnThoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThoatMousePressed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/hr.gif"));
        if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "<html><strong style='font-size'>Bạn có thực sự muốn thoát?</strong></html>", "Form System", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon)) {
            System.exit(0);
        }

    }//GEN-LAST:event_mnThoatMousePressed

    private void mnChucNangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnChucNangMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_mnChucNangMousePressed

    private void mniTacGiaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniTacGiaMouseReleased
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URL("https://www.youtube.com").toURI());
        } catch (Exception ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_mniTacGiaMouseReleased

    private void btDanhMucTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDanhMucTinActionPerformed
          addPanel(new PnCat(),"::Quản Lý Danh Mục Tin::");
    }//GEN-LAST:event_btDanhMucTinActionPerformed

    private void mniTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTrangChuActionPerformed
        addPanel(pnMain, "::NewApp::");
    }//GEN-LAST:event_mniTrangChuActionPerformed

    private void btNguoidungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNguoidungMousePressed
        // TODO add your handling code here:
        addPanel(new PnUser(), "::Quản Lý Người Dùng::");
    }//GEN-LAST:event_btNguoidungMousePressed

    private void btTinTucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTinTucMousePressed
       addPanel(new PnNews(), "::Quản Lý Tin Tức::");
    }//GEN-LAST:event_btTinTucMousePressed

    private void btThemDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemDanhMucActionPerformed
         addPanel(new PnCat(),"::Quản Lý Danh Mục Tin::");
    }//GEN-LAST:event_btThemDanhMucActionPerformed

    private void btThemTinTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemTinTucActionPerformed
        addPanel(new PnNews(), "::Quản Lý Tin Tức::");
    }//GEN-LAST:event_btThemTinTucActionPerformed

    private void btThemNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemNguoiDungActionPerformed
          addPanel(new PnUser(), "::Quản Lý Người Dùng::");
    }//GEN-LAST:event_btThemNguoiDungActionPerformed
    private void addPanel(JPanel pn, String text) {
        lbMsg.setText(text);
        pnCenter.removeAll();
        pnCenter.add(pn, BorderLayout.CENTER);
        // pnCenter.updateUI();
        pnCenter.revalidate();  
        pnCenter.repaint(); 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDanhMucTin;
    private javax.swing.JButton btNguoidung;
    private javax.swing.JButton btThemDanhMuc;
    private javax.swing.JButton btThemNguoiDung;
    private javax.swing.JButton btThemTinTuc;
    private javax.swing.JButton btTinTuc;
    private javax.swing.JLabel lbButtom;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JMenu mnChucNang;
    private javax.swing.JMenu mnThoat;
    private javax.swing.JMenuBar mnbTop;
    private javax.swing.JMenuItem mniTacGia;
    private javax.swing.JMenuItem mniTrangChu;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnLabel;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTop;
    // End of variables declaration//GEN-END:variables
}
