/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.logging.Filter;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Category;
import model.table.CatTable;

/**
 *
 * @author Minh_PC
 */
public class PnCat extends javax.swing.JPanel {

    private CatTable catTable;
    int row = -1;

    /**
     * Creates new form PnCat
     */
    public PnCat() {
        initComponents();
        catTable = new CatTable(tbMain);
        catTable.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitMain = new javax.swing.JSplitPane();
        pnLeft = new javax.swing.JPanel();
        pnTimKiem = new javax.swing.JPanel();
        lbID1 = new javax.swing.JLabel();
        tfIDTK = new javax.swing.JTextField();
        lbTenDanhMuc1 = new javax.swing.JLabel();
        tfTenDanhMucTK = new javax.swing.JTextField();
        pnButtonFormTK = new javax.swing.JPanel();
        btTimKiem = new javax.swing.JButton();
        pnChucNang = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lbTenDanhMuc = new javax.swing.JLabel();
        tfTenDanhMuc = new javax.swing.JTextField();
        pnButton = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        ntNhapLai = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        scrollMain = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        splitMain.setOneTouchExpandable(true);

        pnLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        pnLeft.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnLeft.setMinimumSize(new java.awt.Dimension(455, 230));
        pnLeft.setLayout(new java.awt.BorderLayout());

        pnTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Form Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        lbID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbID1.setForeground(new java.awt.Color(204, 51, 0));
        lbID1.setText("ID:");
        lbID1.setPreferredSize(new java.awt.Dimension(8, 28));

        lbTenDanhMuc1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc1.setForeground(new java.awt.Color(255, 51, 0));
        lbTenDanhMuc1.setText("Tên:");
        lbTenDanhMuc1.setPreferredSize(new java.awt.Dimension(8, 28));

        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });
        pnButtonFormTK.add(btTimKiem);

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnButtonFormTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenDanhMuc1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbID1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTimKiemLayout.createSequentialGroup()
                                .addComponent(tfIDTK, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 222, Short.MAX_VALUE))
                            .addComponent(tfTenDanhMucTK))))
                .addContainerGap())
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tfIDTK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenDanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenDanhMucTK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnButtonFormTK, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnLeft.add(pnTimKiem, java.awt.BorderLayout.SOUTH);

        lbID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbID.setForeground(new java.awt.Color(255, 51, 0));
        lbID.setText("ID Danh Mục");
        lbID.setPreferredSize(new java.awt.Dimension(8, 28));

        tfID.setEditable(false);

        lbTenDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc.setForeground(new java.awt.Color(255, 51, 0));
        lbTenDanhMuc.setText("Tên Danh Mục");
        lbTenDanhMuc.setPreferredSize(new java.awt.Dimension(8, 28));

        btThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btThem.setText("Thêm");
        btThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btThemMousePressed(evt);
            }
        });
        pnButton.add(btThem);

        btSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btSuaMousePressed(evt);
            }
        });
        pnButton.add(btSua);

        ntNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ntNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power_off.png"))); // NOI18N
        ntNhapLai.setText("Nhập Lại");
        ntNhapLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ntNhapLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ntNhapLaiMousePressed(evt);
            }
        });
        pnButton.add(ntNhapLai);

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btXoaMousePressed(evt);
            }
        });
        pnButton.add(btXoa);

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTenDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTenDanhMuc)
                            .addGroup(pnChucNangLayout.createSequentialGroup()
                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnLeft.add(pnChucNang, java.awt.BorderLayout.CENTER);

        splitMain.setLeftComponent(pnLeft);

        pnCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh Sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 51))); // NOI18N
        pnCenter.setLayout(new java.awt.BorderLayout());

        tbMain.setAutoCreateRowSorter(true);
        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        tbMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbMainKeyReleased(evt);
            }
        });
        scrollMain.setViewportView(tbMain);

        pnCenter.add(scrollMain, java.awt.BorderLayout.CENTER);

        splitMain.setRightComponent(pnCenter);

        add(splitMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        //lay dong
        setForm();
    }//GEN-LAST:event_tbMainMousePressed

    private void tbMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbMainKeyReleased
        // TODO add your handling code here:
        setForm();
    }//GEN-LAST:event_tbMainKeyReleased

    private void btThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThemMousePressed
        String name = tfTenDanhMuc.getText();
        Category objCat = new Category(name);
        //catTable.addItem(objCat);

        if (isValid("Add", objCat)) {
            if (catTable.addItem(objCat) > 0) {
                JOptionPane.showMessageDialog(null, "Them Thanh Cong");
            }
        }


    }//GEN-LAST:event_btThemMousePressed

    private void btXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaMousePressed
        // TODO add your handling code here:
        row = tbMain.getSelectedRow();
        int id = 0;
        String name = "";
        if (!tfID.getText().equals("")) {
            id = Integer.parseInt(tfID.getText());
            name = tfTenDanhMuc.getText();
        }
        Category ojbCategory = new Category(id, name);
        if (isValid("Del", ojbCategory)) {

            if (catTable.delItem(row, ojbCategory) > 0) {
                JOptionPane.showMessageDialog(null, "Xoa Thanh Cong");
                resetForm();
            }
        }

    }//GEN-LAST:event_btXoaMousePressed

    private void btSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSuaMousePressed
        // TODO add your handling code here:
        row = tbMain.getSelectedRow();
        int id = 0;
        String name = "";//tfTenDanhMuc.getText();
        if (!tfID.getText().equals("")) {
            id = Integer.parseInt(tfID.getText());
            name = tfTenDanhMuc.getText();
        }
        Category ojbCategory = new Category(id, name);

        if (isValid("Edit", ojbCategory)) {

            if (catTable.EditItem(row, ojbCategory) > 0) {
                JOptionPane.showMessageDialog(null, "Sua Thanh Cong");
                resetForm();
            }
        }


    }//GEN-LAST:event_btSuaMousePressed

    private void ntNhapLaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ntNhapLaiMousePressed
        resetForm();
    }//GEN-LAST:event_ntNhapLaiMousePressed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        //Filter:timf kiems thong qua table trong model ko tuong tac qua co so du lieu
        // TẠo ra một TAbleRowSorter: để wuy định kiểu dữ  liệu tìm kiếm trong model 

        TableRowSorter sorter = new TableRowSorter(tbMain.getModel());
        // Tìm kiếm theo tuwnmgf dòng trong table......Lưu ý tablwe tìm kiếm theo String

        tbMain.setRowSorter(sorter);
        String idF = tfIDTK.getText();

        String nameF = tfTenDanhMucTK.getText();
        ArrayList<RowFilter<AbstractTableModel, Object>> alFilter = new ArrayList<>();
        if (!idF.equals("")) {
            RowFilter<AbstractTableModel, Object> filterID = RowFilter.regexFilter("^" + idF + "$", 0);// 
            alFilter.add(filterID);
        }
        RowFilter<AbstractTableModel, Object> filterName = RowFilter.regexFilter("(?i)" + nameF, 1);// ?i ko phan biet hoa thuong
        alFilter.add(filterName);

        // Quy ddinhj tim kiem theo dieu kien va
        RowFilter<AbstractTableModel, Object> filterAND = RowFilter.andFilter(alFilter);
        sorter.setRowFilter(filterAND);
    }//GEN-LAST:event_btTimKiemActionPerformed
    public void setForm() {
        row = tbMain.getSelectedRow();
        String id = tbMain.getValueAt(row, 0).toString();
        String name = tbMain.getValueAt(row, 1).toString();
        tfID.setText(id);
        tfTenDanhMuc.setText(name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbID1;
    private javax.swing.JLabel lbTenDanhMuc;
    private javax.swing.JLabel lbTenDanhMuc1;
    private javax.swing.JButton ntNhapLai;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnButtonFormTK;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JScrollPane scrollMain;
    private javax.swing.JSplitPane splitMain;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfIDTK;
    private javax.swing.JTextField tfTenDanhMuc;
    private javax.swing.JTextField tfTenDanhMucTK;
    // End of variables declaration//GEN-END:variables

    private boolean isValid(String add, Category objCat) {
        switch (add) {
            case "Add":
                if ("".equals(objCat.getName())) {
                    JOptionPane.showConfirmDialog(null, "vui long nhap ten day du");
                    return false;
                }
                break;
            case "Del":
                if (objCat.getIdCat() <= 0) {
                    JOptionPane.showMessageDialog(null, "Vui Long chon dong de xoa");
                    return false;
                }
                break;
            case "Edit":
                if (objCat.getIdCat() <= 0) {
                    JOptionPane.showMessageDialog(null, "Vui Long chon dong de sua");
                    return false;
                }
                if ("".equals(objCat.getName())) {
                    JOptionPane.showConfirmDialog(null, "vui long nhap ten day du");
                    return false;
                }
                break;
        }

        return true;
    }

    private void resetForm() {
        tfID.setText("");
        tfTenDanhMuc.setText("");
    }
}
