/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import model.com.ComboBoxCat;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;
import library.ConvertNgayThang;
import model.bean.Category;
import model.bean.News;

import model.table.NewsTable;

/**
 *
 * @author Minh_PC
 */
public class PnNews extends javax.swing.JPanel {

    NewsTable newsTable;
    int row = -1;
    File file = null;

    /**
     * Creates new form PnNews
     */
    public PnNews() {
        initComponents();
        setIcon("");
        newsTable = new NewsTable(tbMain);
        newsTable.loadTable();
        //load list cat tp cbb
        loadCBBDanhMuc(cbDanhMuc, false, null);
        loadCBBDanhMuc(cbbDanhMucTK, true, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitMain = new javax.swing.JSplitPane();
        pnLeft = new javax.swing.JPanel();
        pnChucNang = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        tfIDNews = new javax.swing.JTextField();
        lbTenDanhMuc = new javax.swing.JLabel();
        tfTenNews = new javax.swing.JTextField();
        pnButton = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        ntNhapLai = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        lbTenDanhMuc2 = new javax.swing.JLabel();
        lbTenDanhMuc3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMoTa = new javax.swing.JTextArea();
        lbTenDanhMuc5 = new javax.swing.JLabel();
        lbTenDanhMuc6 = new javax.swing.JLabel();
        lbTenDanhMuc7 = new javax.swing.JLabel();
        btUpload = new javax.swing.JButton();
        spNgayDang = new javax.swing.JSpinner();
        cbDanhMuc = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        edChiTiet = new javax.swing.JEditorPane();
        lbHinhAnh = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        pnTimKiem = new javax.swing.JPanel();
        pnButtonTK = new javax.swing.JPanel();
        btTiemKiem = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        btTat = new javax.swing.JButton();
        pnChucNangTK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIDTK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTenTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbbDanhMucTK = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        spTo = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spFrom = new javax.swing.JSpinner();
        btActive = new javax.swing.JButton();
        pnTable = new javax.swing.JPanel();
        cbTable = new javax.swing.JScrollPane();
        tbMain = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        splitMain.setOneTouchExpandable(true);

        pnLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Chức Năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        pnLeft.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnLeft.setMinimumSize(new java.awt.Dimension(455, 230));
        pnLeft.setPreferredSize(new java.awt.Dimension(455, 515));
        pnLeft.setLayout(new java.awt.BorderLayout());

        lbID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbID.setForeground(new java.awt.Color(51, 0, 51));
        lbID.setText("ID Tin:");
        lbID.setPreferredSize(new java.awt.Dimension(8, 28));

        tfIDNews.setEditable(false);

        lbTenDanhMuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc.setForeground(new java.awt.Color(51, 0, 51));
        lbTenDanhMuc.setText("Tên Tin:");
        lbTenDanhMuc.setPreferredSize(new java.awt.Dimension(8, 28));

        btThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.gif"))); // NOI18N
        btThem.setText("Thêm");
        btThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btThemMousePressed(evt);
            }
        });
        pnButton.add(btThem);

        btSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-icon.gif"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        pnButton.add(btSua);

        ntNhapLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ntNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power_off.png"))); // NOI18N
        ntNhapLai.setText("Nhập Lại");
        ntNhapLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ntNhapLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ntNhapLaiMousePressed(evt);
            }
        });
        pnButton.add(ntNhapLai);

        btXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hr.gif"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btXoaMousePressed(evt);
            }
        });
        pnButton.add(btXoa);

        lbTenDanhMuc2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc2.setForeground(new java.awt.Color(51, 0, 51));
        lbTenDanhMuc2.setText("Mô Tả: ");
        lbTenDanhMuc2.setPreferredSize(new java.awt.Dimension(8, 28));

        lbTenDanhMuc3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc3.setForeground(new java.awt.Color(51, 0, 51));
        lbTenDanhMuc3.setText("Chi Tiết");
        lbTenDanhMuc3.setPreferredSize(new java.awt.Dimension(8, 28));

        taMoTa.setColumns(20);
        taMoTa.setRows(5);
        jScrollPane1.setViewportView(taMoTa);

        lbTenDanhMuc5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc5.setForeground(new java.awt.Color(51, 0, 51));
        lbTenDanhMuc5.setText("Hình Ảnh:");
        lbTenDanhMuc5.setPreferredSize(new java.awt.Dimension(8, 28));

        lbTenDanhMuc6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc6.setForeground(new java.awt.Color(51, 0, 51));
        lbTenDanhMuc6.setText("Ngày Đăng:");
        lbTenDanhMuc6.setPreferredSize(new java.awt.Dimension(8, 28));

        lbTenDanhMuc7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenDanhMuc7.setForeground(new java.awt.Color(51, 0, 51));
        lbTenDanhMuc7.setText("Danh Mục:");
        lbTenDanhMuc7.setPreferredSize(new java.awt.Dimension(8, 28));

        btUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        btUpload.setText("Upload");
        btUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btUploadMousePressed(evt);
            }
        });

        spNgayDang.setModel(new javax.swing.SpinnerDateModel());
        spNgayDang.setEditor(new javax.swing.JSpinner.DateEditor(spNgayDang, "dd/MM/yyyy HH:mm:ss"));

        cbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        edChiTiet.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(edChiTiet);

        lbHinhAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTenDanhMuc3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(lbTenDanhMuc6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenDanhMuc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenDanhMuc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenDanhMuc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btUpload)
                            .addComponent(spNgayDang, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(cbDanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTenDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTenNews)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addComponent(tfIDNews, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIDNews, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenNews, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addComponent(lbTenDanhMuc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenDanhMuc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spNgayDang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenDanhMuc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenDanhMuc7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTenDanhMuc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnLeft.add(pnChucNang, java.awt.BorderLayout.CENTER);

        splitMain.setLeftComponent(pnLeft);

        pnCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Danh Sách", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 51))); // NOI18N
        pnCenter.setLayout(new java.awt.BorderLayout());

        pnTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Form Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(51, 51, 255))); // NOI18N
        pnTimKiem.setLayout(new java.awt.BorderLayout());

        pnButtonTK.setBackground(new java.awt.Color(102, 102, 255));
        pnButtonTK.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnButtonTK.setForeground(new java.awt.Color(0, 153, 0));
        pnButtonTK.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        btTiemKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTiemKiem.setForeground(new java.awt.Color(51, 0, 102));
        btTiemKiem.setText("Tìm Kiếm");
        btTiemKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTiemKiemActionPerformed(evt);
            }
        });
        pnButtonTK.add(btTiemKiem);

        btNhapLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNhapLai.setForeground(new java.awt.Color(51, 0, 102));
        btNhapLai.setText("Nhập Lại");
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });
        pnButtonTK.add(btNhapLai);

        btTat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btTat.setForeground(new java.awt.Color(51, 0, 102));
        btTat.setText("Tắt");
        btTat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTatActionPerformed(evt);
            }
        });
        pnButtonTK.add(btTat);

        pnTimKiem.add(pnButtonTK, java.awt.BorderLayout.LINE_END);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("ID");

        jLabel2.setText("Tên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Danh Mục");

        cbbDanhMucTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Ngày Đăng");

        spTo.setModel(new javax.swing.SpinnerDateModel());
        spTo.setEditor(new javax.swing.JSpinner.DateEditor(spTo, "dd/MM/yyyy HH:mm:ss"));

        jLabel5.setText("Tên");

        spFrom.setModel(new javax.swing.SpinnerDateModel());
        spFrom.setEditor(new javax.swing.JSpinner.DateEditor(spFrom, "dd/MM/yyyy HH:mm:ss"));

        btActive.setForeground(new java.awt.Color(102, 204, 0));
        btActive.setText("v");
        btActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChucNangTKLayout = new javax.swing.GroupLayout(pnChucNangTK);
        pnChucNangTK.setLayout(pnChucNangTKLayout);
        pnChucNangTKLayout.setHorizontalGroup(
            pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChucNangTKLayout.createSequentialGroup()
                        .addComponent(tfIDTK, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbDanhMucTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnChucNangTKLayout.createSequentialGroup()
                        .addComponent(spFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spTo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btActive)))
                .addContainerGap())
        );
        pnChucNangTKLayout.setVerticalGroup(
            pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfIDTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbbDanhMucTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(spFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChucNangTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(spTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btActive)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnTimKiem.add(pnChucNangTK, java.awt.BorderLayout.CENTER);

        pnCenter.add(pnTimKiem, java.awt.BorderLayout.NORTH);

        pnTable.setLayout(new java.awt.BorderLayout());

        tbMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMainMousePressed(evt);
            }
        });
        cbTable.setViewportView(tbMain);

        pnTable.add(cbTable, java.awt.BorderLayout.CENTER);

        pnCenter.add(pnTable, java.awt.BorderLayout.CENTER);

        splitMain.setRightComponent(pnCenter);

        add(splitMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMainMousePressed
        setForm();
    }//GEN-LAST:event_tbMainMousePressed

    private void btThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThemMousePressed
        String name = tfTenNews.getText();
        String preview_text = taMoTa.getText();
        String detail_text = edChiTiet.getText();
        String picture = "";
        Category objCat = (Category) cbDanhMuc.getSelectedItem();
        Timestamp date_create = ConvertNgayThang.connvertDatetoTimeStamp((Date) spNgayDang.getValue());
        if (file != null) {
            Path source = Paths.get(file.getAbsolutePath());
            Path target = Paths.get("file/" + file.getName());
            try {
                Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
                picture = file.getName();

            } catch (IOException ex) {
                Logger.getLogger(PnNews.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
//News new1s = new News(

        News objnews = new News(0, name, preview_text, detail_text, objCat.getIdCat(), picture, date_create, objCat.getName());
        if (isValid("add", objnews)) {
            if (newsTable.addItem(objnews) > 0) {
                JOptionPane.showMessageDialog(null, "Them thanh cong");
                resetForm();
            }
        }
    }//GEN-LAST:event_btThemMousePressed

    private void btUploadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUploadMousePressed
        JFileChooser fc = new JFileChooser();

        if (JFileChooser.APPROVE_OPTION == fc.showDialog(this, "Upload Image")) {
            file = fc.getSelectedFile();
            String fileName = file.getName();
            String filePath = file.getPath();
            setIconTmp(filePath);

        } else {
            file = null;
            //setIconTmp(TOOL_TIP_TEXT_KEY);
        }

    }//GEN-LAST:event_btUploadMousePressed

    private void ntNhapLaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ntNhapLaiMousePressed
        resetForm();
    }//GEN-LAST:event_ntNhapLaiMousePressed

    private void btXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaMousePressed
        row = tbMain.getSelectedRow();
        System.out.println(row);
        if (row >= 0) {
            int id = Integer.parseInt(tfIDNews.getText());
            News objUser = new News(id);
            if (isValid("Del", objUser)) {
                if (newsTable.delItem(row, objUser) > 0) {
                    JOptionPane.showMessageDialog(null, "Xoa Thanh Cong");
                    resetForm();
                }
            }
        }

    }//GEN-LAST:event_btXoaMousePressed

    private void btTiemKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTiemKiemActionPerformed
        TableRowSorter sorter = new TableRowSorter(tbMain.getModel());
        tbMain.setRowSorter(sorter);

        ArrayList<RowFilter<AbstractTableModel, Object>> alFilter = new ArrayList<>();

        String idFind = tfIDTK.getText();
        RowFilter<AbstractTableModel, Object> filterID;
        if (!"".equals(idFind)) {
            filterID = RowFilter.regexFilter("^" + idFind + "$", 0);
        } else {
            filterID = RowFilter.regexFilter(idFind, 0);
        }
        alFilter.add(filterID);

        String tenTK = tfTenTK.getText();
        //System.out.println(tenTK);
        RowFilter<AbstractTableModel, Object> filterName = RowFilter.regexFilter("(?i)" + tenTK, 1);
        alFilter.add(filterName);

// tiem keim theo danh muc
        Category objCat = (Category) cbbDanhMucTK.getSelectedItem();
        if (!"".equals(objCat.getName())) {
            RowFilter<AbstractTableModel, Object> filterCAT = RowFilter.regexFilter("(?i)" + objCat.getName(), 2);
            alFilter.add(filterCAT);
        }

//tim kiem theo thoi gian
        if (spTo.isEnabled()) {
            Timestamp datefrom = ConvertNgayThang.connvertDatetoTimeStamp((Date) spFrom.getValue());
            Timestamp dateto = ConvertNgayThang.connvertDatetoTimeStamp((Date) spTo.getValue());
            RowFilter<AbstractTableModel, Object> filterDateFrom = RowFilter.dateFilter(RowFilter.ComparisonType.AFTER, datefrom, 4);
            RowFilter<AbstractTableModel, Object> filterDateTo = RowFilter.dateFilter(RowFilter.ComparisonType.BEFORE, dateto, 4);
            alFilter.add(filterDateFrom);
            alFilter.add(filterDateTo);
        }

        RowFilter<AbstractTableModel, Object> andFilter = RowFilter.andFilter(alFilter);
        sorter.setRowFilter(andFilter);
        // sorter.setRowFilter(filterID);
    }//GEN-LAST:event_btTiemKiemActionPerformed
    private void btActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActiveActionPerformed
        if (spFrom.isEnabled()) {
            spFrom.setEnabled(false);
            spTo.setEnabled(false);
            btActive.setText("X");
            btActive.setForeground(Color.red);
        } else {
            spFrom.setEnabled(true);
            spTo.setEnabled(true);
            btActive.setText("V");
            btActive.setForeground(Color.green);
        }
    }//GEN-LAST:event_btActiveActionPerformed

    private void btTatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTatActionPerformed
        pnChucNangTK.setVisible(false);
    }//GEN-LAST:event_btTatActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        tbMain.setRowSorter(null);
        tfIDTK.setText("");
        tfTenTK.setText("");
        spFrom.setValue(new Date());
        spTo.setValue(new Date());
    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        row = tbMain.getSelectedRow();
        News objnews = new News();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "chon dong de sua");
            return;
        } else {
            objnews = newsTable.getNewFormRow(row);
        }
        // xu ly anh

        String oldPicture = objnews.getPicture();
        String picture = "";
        if ("".equals(oldPicture)) {
            File file = new File("/file" + oldPicture);
            file.delete();
        }
        //upload anh moi

        if (file != null) {
            Path source = Paths.get(file.getAbsolutePath());
            picture = "NewApp-" + System.nanoTime() + "-" + file.getName();
            Path target = Paths.get("file/" + picture);
            try {
                Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
                //picture = file.getAbsolutePath();
                setIconTmp(picture);
            } catch (IOException ex) {
                Logger.getLogger(PnNews.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        int id = Integer.parseInt(tfIDNews.getText());
        String name = tfTenNews.getText();
        String preview_text = taMoTa.getText();
        String detail_text = edChiTiet.getText();
        System.out.println(spNgayDang.getValue());
        //System.out.println(cbDanhMuc.getSelectedItem());
        Category objCat = (Category) cbDanhMuc.getSelectedItem();
        System.out.println("id cua news la " + objCat.getIdCat());
        System.out.println("DAnh muc cua news la " + objCat.getName());

        Timestamp date_create = ConvertNgayThang.connvertDatetoTimeStamp((Date) spNgayDang.getValue());
        System.out.println("Ngay Dang la " + date_create);

        //objnews= new News(id, name, preview_text, detail_text, id, picture, date_create, name)
        objnews = new News(id, name, preview_text, detail_text, objCat.getIdCat(), picture, date_create, objCat.getName());
        if (isValid("Edit", objnews)) {
            if (newsTable.EditItem(row, objnews) > 0) {
                JOptionPane.showMessageDialog(null, "Sua thanh cong");
                resetForm();
            }
        }

    }//GEN-LAST:event_btSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActive;
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btTat;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTiemKiem;
    private javax.swing.JButton btUpload;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbDanhMuc;
    private javax.swing.JScrollPane cbTable;
    private javax.swing.JComboBox<String> cbbDanhMucTK;
    private javax.swing.JEditorPane edChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHinhAnh;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbTenDanhMuc;
    private javax.swing.JLabel lbTenDanhMuc2;
    private javax.swing.JLabel lbTenDanhMuc3;
    private javax.swing.JLabel lbTenDanhMuc5;
    private javax.swing.JLabel lbTenDanhMuc6;
    private javax.swing.JLabel lbTenDanhMuc7;
    private javax.swing.JButton ntNhapLai;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnButtonTK;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnChucNangTK;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnTable;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JSpinner spFrom;
    private javax.swing.JSpinner spNgayDang;
    private javax.swing.JSpinner spTo;
    private javax.swing.JSplitPane splitMain;
    private javax.swing.JTextArea taMoTa;
    private javax.swing.JTable tbMain;
    private javax.swing.JTextField tfIDNews;
    private javax.swing.JTextField tfIDTK;
    private javax.swing.JTextField tfTenNews;
    private javax.swing.JTextField tfTenTK;
    // End of variables declaration//GEN-END:variables

    private void setForm() {
        row = tbMain.getSelectedRow();
        News objNews = newsTable.getNewFormRow(row);
        tfIDNews.setText(String.valueOf(objNews.getId()));
        tfTenNews.setText(objNews.getName());
        taMoTa.setText(objNews.getPreviiew_text());
        spNgayDang.setValue(objNews.getDate_create());
        Category objCat = new Category(objNews.getId_cat(), objNews.getCname());
        cbDanhMuc.setSelectedItem(objCat);
        String picture = objNews.getPicture();
        setIcon(picture);
        edChiTiet.setText(objNews.getDetail_text());
        loadCBBDanhMuc(cbDanhMuc, false, objCat);

    }

    private void loadCBBDanhMuc(JComboBox<String> cbDanhMuc, boolean isSearch, Category objCat) {
        cbDanhMuc.setModel(new ComboBoxCat(isSearch, objCat));
    }

    private boolean isValid(String add, News objCat) {
        switch (add) {
            case "Add":
                if ("".equals(objCat.getName())) {
                    JOptionPane.showConfirmDialog(null, "vui long nhap ten tin");
                    return false;
                }
                if ("".equals(objCat.getDetail_text())) {
                    JOptionPane.showConfirmDialog(null, "vui long nhap mo ta");
                    return false;
                }
                break;
            case "Del":
                if (objCat.getId() < 0) {
                    JOptionPane.showMessageDialog(null, "Vui Long chon dong de xoa");
                    return false;
                }
                break;

            case "Edit":
                if ("".equals(objCat.getName())) {
                    JOptionPane.showConfirmDialog(null, "vui long nhap ten tin");
                    return false;
                }
                if ("".equals(objCat.getDetail_text())) {
                    JOptionPane.showConfirmDialog(null, "vui long nhap mo ta");
                    return false;
                }
                break;

        }
        return true;
    }

    private void resetForm() {
        tfIDNews.setText("");
        tfTenNews.setText("");
        taMoTa.setText("");
        spNgayDang.setValue(new Date());
        // cbDanhMuc.setSelectedItem(objCat);
        edChiTiet.setText("");
        loadCBBDanhMuc(cbDanhMuc, false, null);
        setIcon("");
        tbMain.clearSelection();
    }

    private void setIcon(String fileName) {
        if ("".equals(fileName)) {
            Image image = new ImageIcon(getClass().getResource("/imagess/Imagehere.jpg")).getImage();
            lbHinhAnh.setIcon(new ImageIcon(image.getScaledInstance(180, 105, Image.SCALE_SMOOTH)));

        } else {
            Image image = new ImageIcon("file/" + fileName).getImage();
            lbHinhAnh.setIcon(new ImageIcon(image.getScaledInstance(180, 105, Image.SCALE_SMOOTH)));

        }
    }

    private void setIconTmp(String filePath) {
        Image image = new ImageIcon(filePath).getImage();
        lbHinhAnh.setIcon(new ImageIcon(image.getScaledInstance(147, 100, Image.SCALE_SMOOTH)));
    }
}
