/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeListenerProxy;
import java.io.File;


import java.util.Arrays;

import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.basic.BasicColorChooserUI;

/**
 *
 * @author Minh_PC
 */
public class HocVien extends javax.swing.JFrame {

    private final ButtonGroup buttonGroupGen = new ButtonGroup();
     JSplitPane spcenCenter;
     
     // cach fix loi final
     //tro this trong cai hoc vien
    /**
     * Creates new form BaiTap01
     */
    public HocVien() {
        initComponents();
        initalComponets();

    }

    private void initalComponets() {
        spcenCenter= new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, PanelLeft, PanelRight);
        spcenCenter.setOneTouchExpandable(true);
        PanelCenter.add(spcenCenter,SwingConstants.CENTER);
        PanelLeft.setMaximumSize(new Dimension(320, HEIGHT));// set de keo nho lai ben traai
        PanelRight.setMaximumSize(new Dimension(250, HEIGHT));
        
        // bat su kien tinh dien tich khoan khong gian hinh chu nhat khi di chuyen khoan cach split
        
       
        spcenCenter.addPropertyChangeListener(JSplitPane.DIVIDER_LOCATION_PROPERTY, new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
               // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             int location=Integer.parseInt(evt.getNewValue().toString());
             
                System.out.println(location);
            }
        });
        
        
        Icon icon = new ImageIcon(getClass().getResource("/Image/student.png"));
        // getclass= SCD03_BasicCom..       
        lbTTHV.setIcon(icon);

        //set boder cho panel center
        Border border = BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(),
                "THONG TIN HOC VIEN", TitledBorder.LEFT, TitledBorder.ABOVE_TOP,
                new Font("Tahoma", Font.BOLD, 13), Color.blue);
        PanelCenter.setBorder(border);

        //set item
        /*  PanelCenter.setBorder(border);
        CbbLop.addItem("16CNTT1");
        CbbLop.addItem("16CNTT2");
        CbbLop.addItem("16CNTT3");
        CbbLop.addItem("17CNTT1");
         */
        //2
        List<String> item = Arrays.asList("===chon lop====", "16CNTT1", "16CNTT2", "16CNTT3", "17CNTT1");
        //3
        DefaultComboBoxModel aModel = new DefaultComboBoxModel(item.toArray());

        //1
        CbbLop.setModel(aModel);

        //bt group
        jrbNam.setActionCommand("Nam");
        jrbNu.setActionCommand("Nu");
        jrbKhac.setActionCommand("Khac");
        buttonGroupGen.add(jrbNam);
        buttonGroupGen.add(jrbNu);
        buttonGroupGen.add(jrbKhac);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        PanelMain = new javax.swing.JPanel();
        PanelHead = new javax.swing.JPanel();
        lbTTHV = new javax.swing.JLabel();
        PanelFooterl = new javax.swing.JPanel();
        jButtonSubmit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        PanelCenter = new javax.swing.JPanel();
        PanelLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CbbLop = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrbNu = new javax.swing.JRadioButton();
        jrbNam = new javax.swing.JRadioButton();
        jrbKhac = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jcbDab = new javax.swing.JCheckBox();
        jcbXb = new javax.swing.JCheckBox();
        jcbDb = new javax.swing.JCheckBox();
        PanelRight = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDiemToan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiemVan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaNhanXet = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jlimage = new javax.swing.JLabel();
        jButtonUpload = new javax.swing.JButton();

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain.setLayout(new java.awt.BorderLayout());

        PanelHead.setBackground(new java.awt.Color(255, 255, 255));
        PanelHead.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 25, 1));
        PanelHead.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        lbTTHV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTTHV.setForeground(new java.awt.Color(0, 0, 255));
        lbTTHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/student_adv.png"))); // NOI18N
        lbTTHV.setText("Thong tin Hoc Vien");
        PanelHead.add(lbTTHV);

        PanelMain.add(PanelHead, java.awt.BorderLayout.NORTH);

        PanelFooterl.setBackground(new java.awt.Color(255, 255, 255));
        PanelFooterl.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 1, 10, 1));

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSubmitMousePressed(evt);
            }
        });
        PanelFooterl.add(jButtonSubmit);

        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonResetMousePressed(evt);
            }
        });
        PanelFooterl.add(jButtonReset);

        PanelMain.add(PanelFooterl, java.awt.BorderLayout.SOUTH);

        PanelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thong Tin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 204, 0))); // NOI18N
        PanelCenter.setLayout(new java.awt.BorderLayout());

        PanelLeft.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ho Ten: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Lop: ");

        CbbLop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16CNTT01", "16CNTT02", "16CNTT03", "16CNC", "16SPT" }));
        CbbLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbLopActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gioi Tinh: ");

        jrbNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbNu.setText("Nu");

        jrbNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbNam.setSelected(true);
        jrbNam.setText("Nam");

        jrbKhac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbKhac.setText("Khac");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("So Thich: ");

        jcbDab.setText("Da Bong");

        jcbXb.setText("Xem Bong");

        jcbDb.setText("Di Bong");

        javax.swing.GroupLayout PanelLeftLayout = new javax.swing.GroupLayout(PanelLeft);
        PanelLeft.setLayout(PanelLeftLayout);
        PanelLeftLayout.setHorizontalGroup(
            PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTen)
                    .addComponent(CbbLop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLeftLayout.createSequentialGroup()
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbNu)
                            .addComponent(jcbDab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbNam)
                            .addComponent(jcbXb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLeftLayout.createSequentialGroup()
                                .addComponent(jcbDb)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(PanelLeftLayout.createSequentialGroup()
                                .addComponent(jrbKhac)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        PanelLeftLayout.setVerticalGroup(
            PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLeftLayout.createSequentialGroup()
                .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(CbbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jrbNu)
                            .addComponent(jrbNam)
                            .addComponent(jrbKhac))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jcbDab)
                            .addComponent(jcbXb)
                            .addComponent(jcbDb)))
                    .addGroup(PanelLeftLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3))
                    .addGroup(PanelLeftLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel4)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        PanelCenter.add(PanelLeft, java.awt.BorderLayout.LINE_START);

        PanelRight.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Diem Toan:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Diem Van:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nhan Xet:");

        jtaNhanXet.setColumns(20);
        jtaNhanXet.setLineWrap(true);
        jtaNhanXet.setRows(5);
        jtaNhanXet.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaNhanXet);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Avatar:");

        jlimage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 2, true));

        jButtonUpload.setText("Upload");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRightLayout = new javax.swing.GroupLayout(PanelRight);
        PanelRight.setLayout(PanelRightLayout);
        PanelRightLayout.setHorizontalGroup(
            PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelRightLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51)))
                .addGap(18, 18, 18)
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDiemVan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDiemToan)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(PanelRightLayout.createSequentialGroup()
                        .addComponent(jlimage, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonUpload)))
                .addContainerGap())
        );
        PanelRightLayout.setVerticalGroup(
            PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtDiemToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiemVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRightLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRightLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)))
                .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRightLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel8))
                    .addGroup(PanelRightLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUpload)
                            .addComponent(jlimage, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelCenter.add(PanelRight, java.awt.BorderLayout.CENTER);

        PanelMain.add(PanelCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbbLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbLopActionPerformed

    private void jButtonSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubmitMousePressed
        // TODO add your handling code here:

        String username = txtTen.getText();
        String clas = CbbLop.getSelectedItem().toString();
        String gende = "";

        /* Cach 1:
        
        if(jrbNu.isSelected()){
            gende="Nu";
        }
        if(jrbNam.isSelected()){
            gende="Nam";
        }
        
        if(jrbKhac.isSelected()){
            gende="Khac";
        }
        
         */
        //cach 2: 
        /* Enumeration<AbstractButton> elements = buttonGroupGen.getElements();
        //kiem tra xem con phan tu nao ko? - has more
        while (elements.hasMoreElements()) {
            AbstractButton element = elements.nextElement();
            if (element.isSelected()) {
                gende = element.getText();
            }

        }
         */
        //cach 3:
        gende = buttonGroupGen.getSelection().getActionCommand();
        System.out.println(gende);

    }//GEN-LAST:event_jButtonSubmitMousePressed

    private void jButtonResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMousePressed
      // JOptionPane.showInternalMessageDialog(null, "Click reset button!");
     Icon icon1 = new ImageIcon(getClass().getResource("/Image/student.png"));
     int i=JOptionPane.showConfirmDialog(null,"Click reset button!", "Form System",
              JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,icon1);
     if(JOptionPane.YES_OPTION== i){
         System.out.println("Yes");
         // set text lai mac dinh
         CbbLop.setSelectedIndex(0);
         txtTen.requestFocus();
     }
     else{
         System.out.println("No");
     }
    // JOptionPane.showInputDialog("In"); //tim hieu thang ni lay gia tri nhu the nao
        
    }//GEN-LAST:event_jButtonResetMousePressed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        //if(fc.showDialog(null,"XYZZ"))
        if(JFileChooser.APPROVE_OPTION==fc.showDialog(null,"Upload")){
            System.err.println("111111");
            File file= fc.getSelectedFile();
            
            // set size anh, bat loi file anh bang regex
            String filePath= file.getAbsolutePath();
            //get SaledIntace(100,100,Image.SCRlE_Sno
           // ImageIcon ima= new ImageIcon((filePath).getImage().getSrac
            //check file co pahila file hiknh hay ko, check size cua hinh 
            System.out.println("File: "+file.getParentFile());
            
            
            
             Icon icon3 = new ImageIcon(file.getAbsolutePath());
        // getclass= SCD03_BasicCom..       
        jlimage.setIcon(icon3);
            
        }
        
        
    }//GEN-LAST:event_jButtonUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windown".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HocVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbLop;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelFooterl;
    private javax.swing.JPanel PanelHead;
    private javax.swing.JPanel PanelLeft;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelRight;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbDab;
    private javax.swing.JCheckBox jcbDb;
    private javax.swing.JCheckBox jcbXb;
    private javax.swing.JLabel jlimage;
    private javax.swing.JRadioButton jrbKhac;
    private javax.swing.JRadioButton jrbNam;
    private javax.swing.JRadioButton jrbNu;
    private javax.swing.JTextArea jtaNhanXet;
    private javax.swing.JLabel lbTTHV;
    private javax.swing.JTextField txtDiemToan;
    private javax.swing.JTextField txtDiemVan;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

}
